### ISSUE TITLE
Fontist aborting on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#323]
https://github.com/metanorma/metanorma/actions/runs/6262165634/job/17004059138?pr=322

**Comment by CAMOBAP** [comment]
@alexeymorozov I trying to reprodce the issue locally, but no success. I assume that fontist can find required fonts in some pathes (outside of ~/.fontist or ~/.metanorma/fonts)

Can I somehow restrcit fontist seach path in runtime to simulate the issue?

**Comment by opoudjis** [comment]
Concerned this will get in the way of today's release. We'll find out soon.

**Comment by alexeymorozov** [comment]
Starting to research the issue too.

**Comment by opoudjis** [comment]
Issue still not resolved:

https://github.com/metanorma/metanorma/actions/runs/6455260148/job/17522438248

**Comment by alexeymorozov** [comment]
I discussed with @CAMOBAP a root of the issue, I think, it's being fixed now.

**Comment by opoudjis** [comment]
@alexeymorozov @CAMOBAP This is still not fixed, and it has been a month. I depend on GHA for metanorma development. PLEASE advise what is happening with this ticket.

**Comment by alexeymorozov** [comment]
@opoudjis Restored [the original fix](https://github.com/metanorma/metanorma/commit/f0edaaca79c0b2299d08060e29364aee498cb073) in #336. I hope it would help again (CI is green of course). Please take into account that it was overwritten during refactoring in the a1d14e5 merge commit.

**Comment by CAMOBAP** [comment]
@alexeymorozov thanks

**Comment by opoudjis** [comment]
Yup, can confirm that PRs are green again. Thank you @alexeymorozov and @CAMOBAP !
